In [16]:
# 采用pytorch中提供的模型构建线性回归算法
import torch
import torch.nn as nn
from torch.nn import init
import torch.optim as optim

import data_dj
import torch.utils.data as Data

In [19]:
features, labels = data_dj.create_data(1000, 2)
batch_size = 10
# 将训练数据的特征和标签组合
dataset = Data.TensorDataset(features, labels)
# 随机读取小小批量量
data_iter = Data.DataLoader(dataset, batch_size, shuffle=True)

In [5]:
class LinearNet(nn.Module):
    def __init__(self, n_feature):
        super(LinearNet, self).__init__()
        self.linear = nn.Linear(n_feature, 1)
        
    def forward(self, x):
        y = self.linear(x)
        return y

net = LinearNet(2)
print(net)

LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


In [7]:
param = net.parameters()
for para in param:
    print(para)

Parameter containing:
tensor([[-0.6050, -0.0079]], requires_grad=True)
Parameter containing:
tensor([0.2934], requires_grad=True)


In [17]:
net = nn.Sequential(
    nn.Linear(2, 1)
    # 此处还可以传入入其他层
    )
print(net, net[0])
# 初始化参数
init.normal_(net[0].weight, mean=0, std=0.01)
init.constant_(net[0].bias, val=0)

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
) Linear(in_features=2, out_features=1, bias=True)


Parameter containing:
tensor([0.], requires_grad=True)

In [18]:
# 损失函数以及优化函数
loss = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr=0.03)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [20]:
num_epochs = 3
for epoch in range(1, num_epochs + 1):
    for X, y in data_iter:
        output = net(X)
        l = loss(output, y.view(-1, 1))
        optimizer.zero_grad() # 梯度清零,等价于net.zero_grad()
        l.backward()
        optimizer.step()
    print('epoch %d, loss: %f' % (epoch, l.item()))

epoch 1, loss: 0.000250
epoch 2, loss: 0.000093
epoch 3, loss: 0.000064
