In [1]:
import torch
import torch.nn as nn

In [4]:
class MLP(nn.Module):
    def __init__(self, **kwargs):
        super(MLP, self).__init__(**kwargs)
        self.hidden = nn.Linear(784, 256)
        self.act = nn.ReLU()
        self.output = nn.Linear(256, 10)
    
    def forward(self, x):
        a = self.act(self.hidden(x))
        return self.output(a)

In [5]:
X = torch.rand(2, 784)
net = MLP()
print(net)
net(X)

MLP(
  (hidden): Linear(in_features=784, out_features=256, bias=True)
  (act): ReLU()
  (output): Linear(in_features=256, out_features=10, bias=True)
)


tensor([[ 0.0578, -0.1023, -0.1712, -0.1410,  0.0493,  0.2017,  0.0030, -0.1901,
          0.1259,  0.2295],
        [ 0.0454, -0.0966, -0.0860, -0.1188, -0.0495,  0.3329,  0.0577, -0.1872,
         -0.0081,  0.3338]], grad_fn=<AddmmBackward>)

In [6]:
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[-0.0180,  0.0013,  0.0239,  ..., -0.0023, -0.0035,  0.0151],
                      [ 0.0086, -0.0143, -0.0047,  ..., -0.0155,  0.0150, -0.0262],
                      [-0.0257, -0.0066, -0.0201,  ...,  0.0356,  0.0247,  0.0242],
                      ...,
                      [-0.0332,  0.0017,  0.0074,  ..., -0.0243,  0.0063,  0.0114],
                      [ 0.0010,  0.0315,  0.0336,  ...,  0.0139,  0.0259,  0.0075],
                      [-0.0251, -0.0174,  0.0086,  ...,  0.0299,  0.0233, -0.0143]])),
             ('hidden.bias',
              tensor([-0.0011, -0.0286,  0.0279,  0.0114,  0.0031,  0.0203,  0.0246,  0.0168,
                      -0.0025,  0.0154, -0.0066,  0.0120,  0.0136,  0.0147, -0.0169, -0.0127,
                       0.0129,  0.0196,  0.0322, -0.0293,  0.0269, -0.0208, -0.0183,  0.0278,
                       0.0301,  0.0025,  0.0340, -0.0275,  0.0184,  0.0101,  0.0094, -0.0133,
                       0.0278,